site_name: MKDocs with Cloud Cannon tutorial

#theme: readthedocs
 #user_color_mode_toggle: True

theme:
  name: material
 
nav:
 - Intro: index.md
 - "Github Setup": github-setup.md
 - "Cloud Cannon Setup": CC-setup.md
 
markdown_extensions:
 - smarty
 