site_name: MKDocs with Cloud Cannon tutorial

#theme: readthedocs
 #user_color_mode_toggle: True
 
 theme:
  name: readthedocs
 
nav:
 - Intro: intro.md
 - "Github Setup": github-setup.md
 
markdown_extensions:
 - smarty
 